# Generated by Django 4.2.5 on 2023-09-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='postcode',
            field=models.PositiveIntegerField(),
        ),
    ]
